# -*- coding: utf-8 -*-
import sqlite3
import os
import json

db_dir = os.path.join(os.path.dirname(__file__), 'db')
os.makedirs(db_dir, exist_ok=True)
db_path = os.path.join(db_dir, 'izakaya.db')

MENU_ITEMS_JSON = '''[
    {
        "item_id": "menu-item-hiyayakko",
        "category": "alacarte",
        "badge": "まずはこれから!?",
        "title": "冷やっこ",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-edamame",
        "category": "alacarte",
        "badge": "とりあえずに",
        "title": "枝豆",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-kimchi",
        "category": "alacarte",
        "badge": null,
        "title": "白菜キムチ",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-morokyu",
        "category": "alacarte",
        "badge": null,
        "title": "モロキュー",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yamamotanzaku",
        "category": "alacarte",
        "badge": null,
        "title": "山芋たんざく",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-dashimaki",
        "category": "alacarte",
        "badge": "もちろん手作り",
        "title": "だし巻き玉子",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-hiyashitomato",
        "category": "alacarte",
        "badge": null,
        "title": "冷やしトマト",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tsukemono",
        "category": "alacarte",
        "badge": null,
        "title": "漬物盛り合わせ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-kizushi",
        "category": "alacarte",
        "badge": null,
        "title": "キズシ",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tataki",
        "category": "alacarte",
        "badge": null,
        "title": "地鶏のたたき",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-cheeseomelet",
        "category": "alacarte",
        "badge": null,
        "title": "チーズオムレツ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-mizugyoza",
        "category": "alacarte",
        "badge": "ごま油がたまらない！",
        "title": "水ギョーザ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tomatosalad",
        "category": "salad",
        "badge": null,
        "title": "トマトサラダ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-potatosalad",
        "category": "salad",
        "badge": null,
        "title": "手作りポテトサラダ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-caesarsalad",
        "category": "salad",
        "badge": null,
        "title": "シーザーサラダ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tokusensalad",
        "category": "salad",
        "badge": "当店一番人気のサラダ",
        "title": "一休特選サラダ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-ageshumai",
        "category": "fry",
        "badge": null,
        "title": "揚げシューマイ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-frenchfries",
        "category": "fry",
        "badge": "みんな大好き！",
        "title": "フライドポテト",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-isobe",
        "category": "fry",
        "badge": null,
        "title": "ちくわの磯辺揚げ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-croquette",
        "category": "fry",
        "badge": "すべて手作りです",
        "title": "特製コロッケ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-surume",
        "category": "fry",
        "badge": "かめばかむほど",
        "title": "スルメの天ぷら",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-koebi",
        "category": "fry",
        "badge": null,
        "title": "小エビの寄せ揚げ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-cheesefry",
        "category": "fry",
        "badge": null,
        "title": "チーズフライ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-kushikatsu",
        "category": "fry",
        "badge": null,
        "title": "串カツ盛り合わせ",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-karaage",
        "category": "fry",
        "badge": null,
        "title": "若鶏の唐揚げ",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-torikara-ponzu",
        "category": "fry",
        "badge": null,
        "title": "鶏唐のおろしポン酢",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-agedashidofu",
        "category": "fry",
        "badge": null,
        "title": "揚げ出し豆腐",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yamamotenpura",
        "category": "fry",
        "badge": null,
        "title": "山芋の天ぷら",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-mezashi",
        "category": "grill",
        "badge": null,
        "title": "メザシ",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-shishamo",
        "category": "grill",
        "badge": null,
        "title": "子持ちししゃも",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yakigyoza",
        "category": "grill",
        "badge": null,
        "title": "焼きギョーザ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-satsumaage",
        "category": "grill",
        "badge": "宇和島名産のじゃこ天",
        "title": "さつま揚げ",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-shogayaki",
        "category": "grill",
        "badge": null,
        "title": "豚肉の生姜焼",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-atsuageyaki",
        "category": "grill",
        "badge": "ネギと生姜入り",
        "title": "厚揚げ焼",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-buttercorn",
        "category": "stirfry",
        "badge": null,
        "title": "バターコーン",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-moyashitame",
        "category": "stirfry",
        "badge": null,
        "title": "もやし炒め",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-nasumiso",
        "category": "stirfry",
        "badge": null,
        "title": "なすの味噌炒め",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-butakimchi",
        "category": "stirfry",
        "badge": null,
        "title": "豚キムチ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yasaitame",
        "category": "stirfry",
        "badge": null,
        "title": "五目野菜炒め",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-torinabe",
        "category": "hotpot",
        "badge": null,
        "title": "さっぱり鶏鍋",
        "price": 520,
        "tax_price": 572,
        "price_display": "520円",
        "tax_display": "(税込572円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-kimchinabe",
        "category": "hotpot",
        "badge": null,
        "title": "キムチ鍋",
        "price": 520,
        "tax_price": 572,
        "price_display": "520円",
        "tax_display": "(税込572円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yakiudon",
        "category": "meal",
        "badge": null,
        "title": "焼うどん",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-yakisoba",
        "category": "meal",
        "badge": null,
        "title": "焼きそば",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-onigiri",
        "category": "meal",
        "badge": null,
        "title": "田舎おにぎり (2ヶ)",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": "うめ、鮭、おかかの三つから選べます。",
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-norityazuke",
        "category": "meal",
        "badge": null,
        "title": "のり茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-saketyazuke",
        "category": "meal",
        "badge": null,
        "title": "さけ茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-umetyazuke",
        "category": "meal",
        "badge": null,
        "title": "梅茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-torizosui",
        "category": "meal",
        "badge": null,
        "title": "とり雑炊",
        "price": 390,
        "tax_price": 429,
        "price_display": "390円",
        "tax_display": "(税込429円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-umezosui",
        "category": "meal",
        "badge": null,
        "title": "梅雑炊",
        "price": 390,
        "tax_price": 429,
        "price_display": "390円",
        "tax_display": "(税込429円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-draft-medium",
        "category": "beer",
        "badge": null,
        "title": "アサヒスーパードライ 生ビール (中)",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-draft-large",
        "category": "beer",
        "badge": null,
        "title": "アサヒスーパードライ 生ビール (大)",
        "price": 750,
        "tax_price": 825,
        "price_display": "750円",
        "tax_display": "(税込825円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-bottle-medium",
        "category": "beer",
        "badge": null,
        "title": "アサヒスーパードライ 瓶ビール (中)",
        "price": 480,
        "tax_price": 528,
        "price_display": "480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-dryzero",
        "category": "nonalcoholic",
        "badge": null,
        "title": "アサヒ ドライゼロ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tokkuri-sho",
        "category": "sake",
        "badge": null,
        "title": "徳利 (小) (一合)",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-tokkuri-dai",
        "category": "sake",
        "badge": null,
        "title": "徳利 (大) (二合)",
        "price": 640,
        "tax_price": 704,
        "price_display": "640円",
        "tax_display": "(税込704円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-umeshu",
        "category": "umeshu",
        "badge": null,
        "title": "梅酒 (ロック・サワー)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-lemon",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (レモン)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-lime",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ライム)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-calpis",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (カルピス)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-ume",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (梅)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-kyoho",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (巨峰)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-yuzu",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ゆず)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-chuhai-oolong",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ウーロンハイ)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-highball",
        "category": "highball",
        "badge": null,
        "title": "ハイボール",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-wine-half",
        "category": "wine",
        "badge": null,
        "title": "ワイン (ハーフボトル)",
        "price": 1100,
        "tax_price": 1210,
        "price_display": "1,100円",
        "tax_display": "(税込1,210円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-wine-full",
        "category": "wine",
        "badge": null,
        "title": "ワイン (フルボトル)",
        "price": 1800,
        "tax_price": 1980,
        "price_display": "1,800円",
        "tax_display": "(税込1,980円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-jizake-kenbishi",
        "category": "jizake",
        "badge": null,
        "title": "剣菱",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "兵庫県・芳醇旨口",
        "sake_image": "assets/sake_kenbishi.png"
    },
    {
        "item_id": "menu-item-jizake-tosatsuru",
        "category": "jizake",
        "badge": null,
        "title": "土佐鶴",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "高知県・淡麗辛口",
        "sake_image": "assets/sake_tosatsuru.png"
    },
    {
        "item_id": "menu-item-jizake-karatanba",
        "category": "jizake",
        "badge": null,
        "title": "辛丹波",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "兵庫県・淡麗辛口",
        "sake_image": "assets/sake_karatanba.png"
    },
    {
        "item_id": "menu-item-jizake-goshun",
        "category": "jizake",
        "badge": "池田の銘酒",
        "title": "呉春",
        "price": 580,
        "tax_price": 638,
        "price_display": "グラス 580円",
        "tax_display": "(税込638円)",
        "description": null,
        "sake_tag": "大阪府・旨口",
        "sake_image": "assets/sake_goshun.png"
    },
    {
        "item_id": "menu-item-jizake-kubota",
        "category": "jizake",
        "badge": null,
        "title": "久保田 (千寿)",
        "price": 580,
        "tax_price": 638,
        "price_display": "グラス 580円",
        "tax_display": "(税込638円)",
        "description": null,
        "sake_tag": "新潟県・淡麗辛口",
        "sake_image": "assets/sake_kubota.png"
    },
    {
        "item_id": "menu-item-shochu-rock",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (ロック)",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": "※梅/レモン 各+30円(税込33円)、ソーダ +80円(税込88円)追加",
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-shochu-water",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (お湯割り・水割り)",
        "price": 330,
        "tax_price": 363,
        "price_display": "各 330円",
        "tax_display": "(税込363円)",
        "description": "※梅/レモン 各+30円(税込33円)、ソーダ +80円(税込88円)追加",
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-shochu-soda",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (ソーダ割り)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-keep-sho",
        "category": "shochu_keep",
        "badge": "10本毎に1本サービス",
        "title": "焼酎ボトルキープ 小 (900ml)",
        "price": 2200,
        "tax_price": 2420,
        "price_display": "各 2,200円",
        "tax_display": "(税込2,420円)",
        "description": "〈麦〉いいちこ、二階堂　〈芋〉さつま白波、紫尾の露",
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-keep-dai",
        "category": "shochu_keep",
        "badge": "10本毎に1本サービス",
        "title": "焼酎ボトルキープ 大 (1800ml)",
        "price": 4200,
        "tax_price": 4620,
        "price_display": "各 4,200円",
        "tax_display": "(税込4,620円)",
        "description": "〈麦〉いいちこ、二階堂　〈芋〉さつま白波、黒霧島、ぼっけもん、紫尾の露",
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-soft-oolong",
        "category": "softdrink",
        "badge": null,
        "title": "ウーロン茶",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-soft-calpis",
        "category": "softdrink",
        "badge": null,
        "title": "カルピスウォーター",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    },
    {
        "item_id": "menu-item-soft-cola",
        "category": "softdrink",
        "badge": null,
        "title": "コーラ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null
    }
]'''

def init_db():
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Drop old tables if they exist
    cursor.execute('DROP TABLE IF EXISTS menu_items')
    cursor.execute('DROP TABLE IF EXISTS sake_items')

    # Create new unified menu_items table
    cursor.execute('''
    CREATE TABLE menu_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        item_id TEXT UNIQUE NOT NULL,
        category TEXT NOT NULL,
        badge TEXT,
        title TEXT NOT NULL,
        price INTEGER,
        tax_price INTEGER,
        price_display TEXT NOT NULL,
        tax_display TEXT NOT NULL,
        description TEXT,
        sake_tag TEXT,
        sake_image TEXT
    )
    ''')

    items = json.loads(MENU_ITEMS_JSON)

    # Insert items
    for item in items:
        cursor.execute('''
        INSERT INTO menu_items 
        (item_id, category, badge, title, price, tax_price, price_display, tax_display, description, sake_tag, sake_image)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            item['item_id'],
            item['category'],
            item['badge'],
            item['title'],
            item['price'],
            item['tax_price'],
            item['price_display'],
            item['tax_display'],
            item['description'],
            item['sake_tag'],
            item['sake_image']
        ))

    conn.commit()
    conn.close()
    print("Database initialized successfully at:", db_path)

if __name__ == '__main__':
    init_db()
