# -*- coding: utf-8 -*-
import sqlite3
import os
import json

db_dir = os.path.join(os.path.dirname(__file__), 'db')
os.makedirs(db_dir, exist_ok=True)
db_path = os.path.join(db_dir, 'izakaya.db')

MENU_ITEMS_JSON = '''[
    {
        "item_id": "menu-item-hiyayakko",
        "category": "alacarte",
        "badge": "まずはこれから!?",
        "title": "冷やっこ",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Chilled Tofu (Hiyayakko)",
        "badge_en": "Quick Start!",
        "price_display_en": "280 yen",
        "tax_display_en": "(incl. tax 308 yen)",
        "description_en": "Chilled silken tofu served with grated ginger, scallions, and bonito flakes.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-edamame",
        "category": "alacarte",
        "badge": "とりあえずに",
        "title": "枝豆",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Edamame",
        "badge_en": "Classic!",
        "price_display_en": "280 yen",
        "tax_display_en": "(incl. tax 308 yen)",
        "description_en": "Lightly salted boiled green soybeans. The perfect companion for beer.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-kimchi",
        "category": "alacarte",
        "badge": null,
        "title": "白菜キムチ",
        "price": 280,
        "tax_price": 308,
        "price_display": "280円",
        "tax_display": "(税込308円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Napa Cabbage Kimchi",
        "badge_en": null,
        "price_display_en": "280 yen",
        "tax_display_en": "(incl. tax 308 yen)",
        "description_en": "Spicy fermented napa cabbage.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-morokyu",
        "category": "alacarte",
        "badge": null,
        "title": "モロキュー",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Cucumber with Miso (Morokyu)",
        "badge_en": null,
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Fresh cucumber slices served with rich savory miso paste.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-yamamotanzaku",
        "category": "alacarte",
        "badge": null,
        "title": "山芋たんざく",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Sliced Mountain Yam",
        "badge_en": null,
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Crisp sliced raw mountain yam.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-dashimaki",
        "category": "alacarte",
        "badge": "もちろん手作り",
        "title": "だし巻き玉子",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Rolled Omelet (Dashimaki)",
        "badge_en": "Handmade!",
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Traditional handmade rolled omelet seasoned with rich savory dashi broth.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-hiyashitomato",
        "category": "alacarte",
        "badge": null,
        "title": "冷やしトマト",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Chilled Tomato",
        "badge_en": null,
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Refreshing chilled tomato slices.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-tsukemono",
        "category": "alacarte",
        "badge": null,
        "title": "漬物盛り合わせ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Assorted Pickles",
        "badge_en": null,
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Selection of traditional Japanese pickled vegetables.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-kizushi",
        "category": "alacarte",
        "badge": null,
        "title": "キズシ",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Cured Mackerel (Kizushi)",
        "badge_en": null,
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Sliced vinegared mackerel sashimi.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-tataki",
        "category": "alacarte",
        "badge": null,
        "title": "地鶏のたたき",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Seared Local Chicken (Tataki)",
        "badge_en": "Rare Choice",
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Lightly seared premium local chicken served with green onions and ponzu.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-cheeseomelet",
        "category": "alacarte",
        "badge": null,
        "title": "チーズオムレツ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Cheese Omelet",
        "badge_en": null,
        "price_display_en": "420 yen",
        "tax_display_en": "(incl. tax 462 yen)",
        "description_en": "Fluffy omelet filled with melted cheese.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-mizugyoza",
        "category": "alacarte",
        "badge": "ごま油がたまらない！",
        "title": "水ギョーザ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Boiled Gyoza",
        "badge_en": "Sesame Flavor",
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Boiled gyoza dumplings with rich sesame oil dressing.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-tomatosalad",
        "category": "salad",
        "badge": null,
        "title": "トマトサラダ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Tomato Salad",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Fresh tomato slices on seasonal greens with house dressing.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-potatosalad",
        "category": "salad",
        "badge": null,
        "title": "手作りポテトサラダ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Handmade Potato Salad",
        "badge_en": "Handmade!",
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Creamy handmade Japanese-style potato salad.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-caesarsalad",
        "category": "salad",
        "badge": null,
        "title": "シーザーサラダ",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Caesar Salad",
        "badge_en": null,
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Crisp romaine lettuce with Caesar dressing and croutons.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-tokusensalad",
        "category": "salad",
        "badge": "当店一番人気のサラダ",
        "title": "一休特選サラダ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Ikkyu Special Salad",
        "badge_en": "Most Popular!",
        "price_display_en": "420 yen",
        "tax_display_en": "(incl. tax 462 yen)",
        "description_en": "Our most popular salad with assorted toppings and signature dressing.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-ageshumai",
        "category": "fry",
        "badge": null,
        "title": "揚げシューマイ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Shumai",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Deep-fried pork dumplings.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-frenchfries",
        "category": "fry",
        "badge": "みんな大好き！",
        "title": "フライドポテト",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "French Fries",
        "badge_en": "Kids' Choice!",
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Crispy golden potato fries.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-isobe",
        "category": "fry",
        "badge": null,
        "title": "ちくわの磯辺揚げ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Fish Cakes (Isobeage)",
        "badge_en": "Izakaya Classic",
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Chewy chikuwa fish cake tempura flavored with green nori seaweed.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-croquette",
        "category": "fry",
        "badge": "すべて手作りです",
        "title": "特製コロッケ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Special Croquette",
        "badge_en": "Handmade!",
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Handmade crispy potato croquettes.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-surume",
        "category": "fry",
        "badge": "かめばかむほど",
        "title": "スルメの天ぷら",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Dried Squid Tempura",
        "badge_en": "Savory & Chewy",
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Deep-fried dried squid tempura. Excellent with sake or beer.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-koebi",
        "category": "fry",
        "badge": null,
        "title": "小エビの寄せ揚げ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Small Shrimp",
        "badge_en": null,
        "price_display_en": "420 yen",
        "tax_display_en": "(incl. tax 462 yen)",
        "description_en": "Crispy deep-fried small whole river shrimp.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-cheesefry",
        "category": "fry",
        "badge": null,
        "title": "チーズフライ",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Cheese",
        "badge_en": null,
        "price_display_en": "420 yen",
        "tax_display_en": "(incl. tax 462 yen)",
        "description_en": "Melted cheese sticks fried in crispy breadcrumbs.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-kushikatsu",
        "category": "fry",
        "badge": null,
        "title": "串カツ盛り合わせ",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Assorted Kushikatsu",
        "badge_en": "Osaka Specialty",
        "price_display_en": "450 yen",
        "tax_display_en": "(incl. tax 495 yen)",
        "description_en": "Osaka specialty: deep-fried skewered meat and vegetables.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-karaage",
        "category": "fry",
        "badge": null,
        "title": "若鶏の唐揚げ",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Chicken (Karaage)",
        "badge_en": "Best Seller!",
        "price_display_en": "450 yen",
        "tax_display_en": "(incl. tax 495 yen)",
        "description_en": "Crispy and juicy ginger-soy marinated fried chicken.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-torikara-ponzu",
        "category": "fry",
        "badge": null,
        "title": "鶏唐のおろしポン酢",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Chicken with Ponzu",
        "badge_en": null,
        "price_display_en": "450 yen",
        "tax_display_en": "(incl. tax 495 yen)",
        "description_en": "Crispy fried chicken topped with grated daikon radish and citrus ponzu.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-agedashidofu",
        "category": "fry",
        "badge": null,
        "title": "揚げ出し豆腐",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Agedashi Tofu",
        "badge_en": "Classic",
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Deep-fried tofu cubes in hot savory dashi broth.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-yamamotenpura",
        "category": "fry",
        "badge": null,
        "title": "山芋の天ぷら",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Mountain Yam Tempura",
        "badge_en": null,
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Light and crispy mountain yam tempura.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-mezashi",
        "category": "grill",
        "badge": null,
        "title": "メザシ",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Grilled Sardines (Mezashi)",
        "badge_en": null,
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Grilled semi-dried skewered sardines.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-shishamo",
        "category": "grill",
        "badge": null,
        "title": "子持ちししゃも",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Grilled Shishamo",
        "badge_en": null,
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Grilled capelin fish filled with roe.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-yakigyoza",
        "category": "grill",
        "badge": null,
        "title": "焼きギョーザ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Pan-Fried Gyoza",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Crispy pan-fried pork dumplings.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-satsumaage",
        "category": "grill",
        "badge": "宇和島名産のじゃこ天",
        "title": "さつま揚げ",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Fried Fish Cake (Jako-ten)",
        "badge_en": "Uwajima Local Specialty",
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Tasty grilled fish cake from Uwajima.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-shogayaki",
        "category": "grill",
        "badge": null,
        "title": "豚肉の生姜焼",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Ginger Pork (Shogayaki)",
        "badge_en": "Pub Favorite",
        "price_display_en": "450 yen",
        "tax_display_en": "(incl. tax 495 yen)",
        "description_en": "Thinly sliced pork stir-fried in a savory ginger soy sauce.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-atsuageyaki",
        "category": "grill",
        "badge": "ネギと生姜入り",
        "title": "厚揚げ焼",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Grilled Thick Tofu",
        "badge_en": "With Ginger & Scallions",
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Grilled thick tofu served with grated ginger and scallions.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-buttercorn",
        "category": "stirfry",
        "badge": null,
        "title": "バターコーン",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Butter Corn",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Sweet corn kernels sautéed in rich butter.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-moyashitame",
        "category": "stirfry",
        "badge": null,
        "title": "もやし炒め",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Bean Sprout Stir-Fry",
        "badge_en": null,
        "price_display_en": "320 yen",
        "tax_display_en": "(incl. tax 352 yen)",
        "description_en": "Stir-fried bean sprouts with pork.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-nasumiso",
        "category": "stirfry",
        "badge": null,
        "title": "なすの味噌炒め",
        "price": 350,
        "tax_price": 385,
        "price_display": "350円",
        "tax_display": "(税込385円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Eggplant Miso Stir-Fry",
        "badge_en": null,
        "price_display_en": "350 yen",
        "tax_display_en": "(incl. tax 385 yen)",
        "description_en": "Tender eggplant stir-fried in savory sweet miso sauce.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-butakimchi",
        "category": "stirfry",
        "badge": null,
        "title": "豚キムチ",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Pork Kimchi Stir-Fry",
        "badge_en": "Spicy!",
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Spicy stir-fried pork and napa cabbage kimchi.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-yasaitame",
        "category": "stirfry",
        "badge": null,
        "title": "五目野菜炒め",
        "price": 420,
        "tax_price": 462,
        "price_display": "420円",
        "tax_display": "(税込462円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Mixed Vegetable Stir-Fry",
        "badge_en": null,
        "price_display_en": "420 yen",
        "tax_display_en": "(incl. tax 462 yen)",
        "description_en": "Healthy stir-fried assortment of vegetables and pork.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-torinabe",
        "category": "hotpot",
        "badge": null,
        "title": "さっぱり鶏鍋",
        "price": 520,
        "tax_price": 572,
        "price_display": "520円",
        "tax_display": "(税込572円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Chicken Hot Pot",
        "badge_en": "Warm Comfort",
        "price_display_en": "520 yen",
        "tax_display_en": "(incl. tax 572 yen)",
        "description_en": "Clear savory chicken hot pot cooked at your table.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-kimchinabe",
        "category": "hotpot",
        "badge": null,
        "title": "キムチ鍋",
        "price": 520,
        "tax_price": 572,
        "price_display": "520円",
        "tax_display": "(税込572円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Kimchi Hot Pot",
        "badge_en": "Spicy",
        "price_display_en": "520 yen",
        "tax_display_en": "(incl. tax 572 yen)",
        "description_en": "Spicy kimchi broth hot pot with pork and tofu.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-yakiudon",
        "category": "meal",
        "badge": null,
        "title": "焼うどん",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Yaki Udon",
        "badge_en": "Soy Sauce Flavor",
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Stir-fried thick udon noodles with pork and vegetables.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-yakisoba",
        "category": "meal",
        "badge": null,
        "title": "焼きそば",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Yakisoba",
        "badge_en": "Izakaya Classic",
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Stir-fried wheat noodles with pork, vegetables, and savory sauce.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-onigiri",
        "category": "meal",
        "badge": null,
        "title": "田舎おにぎり (2ヶ)",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": "うめ、鮭、おかかの三つから選べます。",
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Country Rice Balls (2 pcs)",
        "badge_en": "Handmade",
        "price_display_en": "320 yen",
        "tax_display_en": "(incl. tax 352 yen)",
        "description_en": "Two handmade rice balls. Choose flavor: Plum, Salmon, or Bonito Flakes.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-norityazuke",
        "category": "meal",
        "badge": null,
        "title": "のり茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Nori Ochazuke",
        "badge_en": "Light Finish",
        "price_display_en": "320 yen",
        "tax_display_en": "(incl. tax 352 yen)",
        "description_en": "Rice in hot green tea/dashi broth topped with nori seaweed.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-saketyazuke",
        "category": "meal",
        "badge": null,
        "title": "さけ茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Salmon Ochazuke",
        "badge_en": "Traditional",
        "price_display_en": "320 yen",
        "tax_display_en": "(incl. tax 352 yen)",
        "description_en": "Rice in hot green tea/dashi broth topped with flaked salmon.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-umetyazuke",
        "category": "meal",
        "badge": null,
        "title": "梅茶漬け",
        "price": 320,
        "tax_price": 352,
        "price_display": "320円",
        "tax_display": "(税込352円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Plum Ochazuke",
        "badge_en": "Sour & Salty",
        "price_display_en": "320 yen",
        "tax_display_en": "(incl. tax 352 yen)",
        "description_en": "Rice in hot green tea/dashi broth topped with pickled plum.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-torizosui",
        "category": "meal",
        "badge": null,
        "title": "とり雑炊",
        "price": 390,
        "tax_price": 429,
        "price_display": "390円",
        "tax_display": "(税込429円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Chicken Rice Porridge",
        "badge_en": null,
        "price_display_en": "390 yen",
        "tax_display_en": "(incl. tax 429 yen)",
        "description_en": "Warm chicken and egg rice porridge.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-umezosui",
        "category": "meal",
        "badge": null,
        "title": "梅雑炊",
        "price": 390,
        "tax_price": 429,
        "price_display": "390円",
        "tax_display": "(税込429円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Plum Rice Porridge",
        "badge_en": null,
        "price_display_en": "390 yen",
        "tax_display_en": "(incl. tax 429 yen)",
        "description_en": "Warm pickled plum and egg rice porridge.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-draft-medium",
        "category": "beer",
        "badge": null,
        "title": "スーパードライ<br>生ビール (中)",
        "price": 450,
        "tax_price": 495,
        "price_display": "450円",
        "tax_display": "(税込495円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Super Dry Draft Beer (M)",
        "badge_en": null,
        "price_display_en": "450 yen",
        "tax_display_en": "(incl. tax 495 yen)",
        "description_en": "Super Dry draft beer (Medium glass).",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-draft-large",
        "category": "beer",
        "badge": null,
        "title": "スーパードライ<br>生ビール (大)",
        "price": 750,
        "tax_price": 825,
        "price_display": "750円",
        "tax_display": "(税込825円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Super Dry Draft Beer (L)",
        "badge_en": null,
        "price_display_en": "750 yen",
        "tax_display_en": "(incl. tax 825 yen)",
        "description_en": "Super Dry draft beer (Large mug).",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-bottle-medium",
        "category": "beer",
        "badge": null,
        "title": "スーパードライ<br>瓶ビール (中)",
        "price": 480,
        "tax_price": 528,
        "price_display": "480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Super Dry Bottled Beer (M)",
        "badge_en": null,
        "price_display_en": "480 yen",
        "tax_display_en": "(incl. tax 528 yen)",
        "description_en": "Super Dry bottled beer (Medium bottle).",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-dryzero",
        "category": "nonalcoholic",
        "badge": null,
        "title": "ドライゼロ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Asahi Dry Zero",
        "badge_en": "Non-Alcoholic",
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Non-alcoholic beer.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-tokkuri-sho",
        "category": "sake",
        "badge": null,
        "title": "徳利 (小) (一合)",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Sake Tokkuri (S) (180ml)",
        "badge_en": "Flask",
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Hot or cold house sake served in a small flask.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-tokkuri-dai",
        "category": "sake",
        "badge": null,
        "title": "徳利 (大) (二合)",
        "price": 640,
        "tax_price": 704,
        "price_display": "640円",
        "tax_display": "(税込704円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Sake Tokkuri (L) (360ml)",
        "badge_en": "Flask",
        "price_display_en": "640 yen",
        "tax_display_en": "(incl. tax 704 yen)",
        "description_en": "Hot or cold house sake served in a large flask.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-umeshu",
        "category": "umeshu",
        "badge": null,
        "title": "梅酒 (ロック・サワー)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Plum Wine (Umeshu)",
        "badge_en": "Sweet & Fruity",
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Sweet Japanese plum wine. Choose: On the Rocks or with Soda.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-chuhai-lemon",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (レモン)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Lemon)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and fresh lemon.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-lime",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ライム)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Lime)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and fresh lime.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-calpis",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (カルピス)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Calpis)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and Calpis yogurt flavor.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-ume",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (梅)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Plum)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and pickled plum.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-kyoho",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (巨峰)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Kyoho Grape)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and Kyoho grape juice.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-yuzu",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ゆず)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Sour (Yuzu)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with soda and aromatic citrus yuzu syrup.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-chuhai-oolong",
        "category": "chuhai",
        "badge": null,
        "title": "チューハイ (ウーロンハイ)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Oolong High",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Shochu mixed with chilled oolong tea.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-highball",
        "category": "highball",
        "badge": null,
        "title": "ハイボール",
        "price": 400,
        "tax_price": 440,
        "price_display": "400円",
        "tax_display": "(税込440円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Whisky Highball",
        "badge_en": "Popular",
        "price_display_en": "400 yen",
        "tax_display_en": "(incl. tax 440 yen)",
        "description_en": "Whisky mixed with refreshing carbonated soda.",
        "sake_tag_en": null,
        "is_recommend_en": 1
    },
    {
        "item_id": "menu-item-wine-half",
        "category": "wine",
        "badge": null,
        "title": "ワイン (ハーフボトル)",
        "price": 1100,
        "tax_price": 1210,
        "price_display": "1,100円",
        "tax_display": "(税込1,210円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Wine (Half Bottle)",
        "badge_en": null,
        "price_display_en": "1,100 yen",
        "tax_display_en": "(incl. tax 1,210 yen)",
        "description_en": "Red or White half bottle wine.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-wine-full",
        "category": "wine",
        "badge": null,
        "title": "ワイン (フルボトル)",
        "price": 1800,
        "tax_price": 1980,
        "price_display": "1,800円",
        "tax_display": "(税込1,980円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Wine (Full Bottle)",
        "badge_en": null,
        "price_display_en": "1,800 yen",
        "tax_display_en": "(incl. tax 1,980 yen)",
        "description_en": "Red or White full bottle wine.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-jizake-kenbishi",
        "category": "jizake",
        "badge": null,
        "title": "剣菱",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "兵庫県・芳醇旨口",
        "sake_image": "assets/sake_kenbishi.png",
        "title_en": "Kenbishi",
        "badge_en": null,
        "price_display_en": "Glass 480 yen",
        "tax_display_en": "(incl. tax 528 yen)",
        "description_en": "Hyogo prefecture • Rich and full-bodied classic sake.",
        "sake_tag_en": "Hyogo • Rich & Dry",
        "is_recommend_en": 1,
        "sake_website": "https://www.kenbishi.co.jp/",
        "sake_website_en": "https://www.kenbishi.co.jp/en/"
    },
    {
        "item_id": "menu-item-jizake-tosatsuru",
        "category": "jizake",
        "badge": null,
        "title": "土佐鶴",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "高知県・淡麗辛口",
        "sake_image": "assets/sake_tosatsuru.png",
        "title_en": "Tosatsuru",
        "badge_en": null,
        "price_display_en": "Glass 480 yen",
        "tax_display_en": "(incl. tax 528 yen)",
        "description_en": "Kochi prefecture • Extremely crisp and dry sake.",
        "sake_tag_en": "Kochi • Crisp & Dry",
        "is_recommend_en": 1,
        "sake_website": "https://www.tosatsuru.co.jp/",
        "sake_website_en": "https://www.tosatsuru.co.jp/"
    },
    {
        "item_id": "menu-item-jizake-karatanba",
        "category": "jizake",
        "badge": null,
        "title": "辛丹波",
        "price": 480,
        "tax_price": 528,
        "price_display": "グラス 480円",
        "tax_display": "(税込528円)",
        "description": null,
        "sake_tag": "兵庫県・淡麗辛口",
        "sake_image": "assets/sake_karatanba.png",
        "title_en": "Karatanba",
        "badge_en": null,
        "price_display_en": "Glass 480 yen",
        "tax_display_en": "(incl. tax 528 yen)",
        "description_en": "Hyogo prefecture • Rich yet clean dry sake.",
        "sake_tag_en": "Hyogo • Clean & Dry",
        "is_recommend_en": 0,
        "sake_website": "https://www.ozeki.co.jp/karatanba/",
        "sake_website_en": "https://www.ozekisake.com/products/karatamba-honjozo/"
    },
    {
        "item_id": "menu-item-jizake-goshun",
        "category": "jizake",
        "badge": "池田の銘酒",
        "title": "呉春",
        "price": 580,
        "tax_price": 638,
        "price_display": "グラス 580円",
        "tax_display": "(税込638円)",
        "description": null,
        "sake_tag": "大阪府・旨口",
        "sake_image": "assets/sake_goshun.png",
        "title_en": "Goshun",
        "badge_en": "Osaka Local Sake",
        "price_display_en": "Glass 580 yen",
        "tax_display_en": "(incl. tax 638 yen)",
        "description_en": "Osaka local specialty sake. Remarkably smooth, mild, and satisfying.",
        "sake_tag_en": "Osaka • Smooth & Mild",
        "is_recommend_en": 1,
        "sake_website": "https://www.sakenomy.jp/brewery/894/",
        "sake_website_en": "https://www.sakenomy.jp/en/brewery/894/"
    },
    {
        "item_id": "menu-item-jizake-kubota",
        "category": "jizake",
        "badge": null,
        "title": "久保田 (千寿)",
        "price": 580,
        "tax_price": 638,
        "price_display": "グラス 580円",
        "tax_display": "(税込638円)",
        "description": null,
        "sake_tag": "新潟県・淡麗辛口",
        "sake_image": "assets/sake_kubota.png",
        "title_en": "Kubota (Senju)",
        "badge_en": "Premium Sake",
        "price_display_en": "Glass 580 yen",
        "tax_display_en": "(incl. tax 638 yen)",
        "description_en": "Niigata prefecture • Super famous premium sake with a clean, crisp finish.",
        "sake_tag_en": "Niigata • Crisp & Clean",
        "is_recommend_en": 1,
        "sake_website": "https://www.asahi-shuzo.co.jp/kubota/senjyu/",
        "sake_website_en": "https://www.asahi-shuzo.co.jp/en/kubota/"
    },
    {
        "item_id": "menu-item-shochu-rock",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (ロック)",
        "price": 330,
        "tax_price": 363,
        "price_display": "330円",
        "tax_display": "(税込363円)",
        "description": "※梅/レモン 各+30円(税込33円)、ソーダ +80円(税込88円)追加",
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu (On the Rocks)",
        "badge_en": null,
        "price_display_en": "330 yen",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Neat distilled Japanese spirit served on the rocks. *Add Plum/Lemon +30 yen (incl. tax 33 yen), Soda +80 yen (incl. tax 88 yen)",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-shochu-water",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (お湯割り・水割り)",
        "price": 330,
        "tax_price": 363,
        "price_display": "各 330円",
        "tax_display": "(税込363円)",
        "description": "※梅/レモン 各+30円(税込33円)、ソーダ +80円(税込88円)追加",
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu (Water / Hot Water)",
        "badge_en": null,
        "price_display_en": "330 yen each",
        "tax_display_en": "(incl. tax 363 yen)",
        "description_en": "Distilled Japanese spirit served with water or hot water. *Add Plum/Lemon +30 yen (incl. tax 33 yen), Soda +80 yen (incl. tax 88 yen)",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-shochu-soda",
        "category": "shochu",
        "badge": null,
        "title": "焼酎 (ソーダ割り)",
        "price": 380,
        "tax_price": 418,
        "price_display": "380円",
        "tax_display": "(税込418円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu (Soda Mix)",
        "badge_en": null,
        "price_display_en": "380 yen",
        "tax_display_en": "(incl. tax 418 yen)",
        "description_en": "Distilled Japanese spirit mixed with carbonated soda.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-keep-sho",
        "category": "shochu_keep",
        "badge": "10本毎に1本サービス",
        "title": "焼酎ボトルキープ 小 (900ml)",
        "price": 2200,
        "tax_price": 2420,
        "price_display": "各 2,200円",
        "tax_display": "(税込2,420円)",
        "description": "〈麦〉いいちこ、二階堂　〈芋〉さつま白波、紫尾の露",
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Bottle Keep Small (900ml)",
        "badge_en": "1 Free per 10 Kept",
        "price_display_en": "2,200 yen each",
        "tax_display_en": "(incl. tax 2,420 yen)",
        "description_en": "Keep a 900ml Shochu bottle. Choose: Barley (Iichiko, Nikaido) or Potato (White Shiranami, Shibinotsuyu).",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-keep-dai",
        "category": "shochu_keep",
        "badge": "10本毎に1本サービス",
        "title": "焼酎ボトルキープ 大 (1800ml)",
        "price": 4200,
        "tax_price": 4620,
        "price_display": "各 4,200円",
        "tax_display": "(税込4,620円)",
        "description": "〈麦〉いいちこ、二階堂　〈芋〉さつま白波、黒霧島、ぼっけもん、紫尾の露",
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Shochu Bottle Keep Large (1800ml)",
        "badge_en": "1 Free per 10 Kept",
        "price_display_en": "4,200 yen each",
        "tax_display_en": "(incl. tax 4,620 yen)",
        "description_en": "Keep a 1800ml Shochu bottle. Choose: Barley (Iichiko, Nikaido) or Potato (White Shiranami, Kurokirishima, Bokkemon, Shibinotsuyu).",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-soft-oolong",
        "category": "softdrink",
        "badge": null,
        "title": "ウーロン茶",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Oolong Tea",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Chilled unsweetened oolong tea.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-soft-calpis",
        "category": "softdrink",
        "badge": null,
        "title": "カルピスウォーター",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Calpis Water",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Sweet, refreshing milk-based lactic acid beverage.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    },
    {
        "item_id": "menu-item-soft-cola",
        "category": "softdrink",
        "badge": null,
        "title": "コーラ",
        "price": 300,
        "tax_price": 330,
        "price_display": "300円",
        "tax_display": "(税込330円)",
        "description": null,
        "sake_tag": null,
        "sake_image": null,
        "title_en": "Coca Cola",
        "badge_en": null,
        "price_display_en": "300 yen",
        "tax_display_en": "(incl. tax 330 yen)",
        "description_en": "Chilled classic Coca-Cola.",
        "sake_tag_en": null,
        "is_recommend_en": 0
    }
]'''

def init_db():
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Drop old tables if they exist
    cursor.execute('DROP TABLE IF EXISTS menu_items')
    cursor.execute('DROP TABLE IF EXISTS sake_items')

    # Create new unified menu_items table with English translation columns
    cursor.execute('''
    CREATE TABLE menu_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        item_id TEXT UNIQUE NOT NULL,
        category TEXT NOT NULL,
        badge TEXT,
        badge_en TEXT,
        title TEXT NOT NULL,
        title_en TEXT NOT NULL,
        price INTEGER,
        tax_price INTEGER,
        price_display TEXT NOT NULL,
        price_display_en TEXT NOT NULL,
        tax_display TEXT NOT NULL,
        tax_display_en TEXT NOT NULL,
        description TEXT,
        description_en TEXT,
        sake_tag TEXT,
        sake_tag_en TEXT,
        sake_image TEXT,
        is_recommend_en INTEGER DEFAULT 0,
        sake_website TEXT,
        sake_website_en TEXT
    )
    ''')

    items = json.loads(MENU_ITEMS_JSON)

    # Insert items
    for item in items:
        cursor.execute('''
        INSERT INTO menu_items 
        (item_id, category, badge, badge_en, title, title_en, price, tax_price, price_display, price_display_en, tax_display, tax_display_en, description, description_en, sake_tag, sake_tag_en, sake_image, is_recommend_en, sake_website, sake_website_en)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            item['item_id'],
            item['category'],
            item['badge'],
            item.get('badge_en'),
            item['title'],
            item.get('title_en', item['title']),
            item['price'],
            item['tax_price'],
            item['price_display'],
            item.get('price_display_en', item['price_display']),
            item['tax_display'],
            item.get('tax_display_en', item['tax_display']),
            item['description'],
            item.get('description_en'),
            item['sake_tag'],
            item.get('sake_tag_en'),
            item['sake_image'],
            item.get('is_recommend_en', 0),
            item.get('sake_website'),
            item.get('sake_website_en')
        ))

    conn.commit()
    conn.close()
    print("Database initialized successfully at:", db_path)

if __name__ == '__main__':
    init_db()
